(deftheme slick
  "Created 2013-10-15.")

(defvar slick-orange-0 "#FFA139")
(defvar slick-orange-1 "#80684E")
(defvar slick-orange-2 "#4D2800")
(defvar slick-orange+1 "#FFD09C")
(defvar slick-orange+2 "#FFF6EB")
(defvar slick-pink-0   "#FF398F")
(defvar slick-pink-1   "#804E64")
(defvar slick-pink-2   "#4D0021")
(defvar slick-pink+1   "#FF9CC7")
(defvar slick-pink+2   "#FFEBF4")
(defvar slick-green-0  "#ABFF39")
(defvar slick-green-1  "#6B804E")
(defvar slick-green-2  "#2C4D00")
(defvar slick-green+1  "#D5FF9C")
(defvar slick-green+2  "#F7FFEB")
(defvar slick-blue-0   "#42C6FF")
(defvar slick-blue-1   "#507180")
(defvar slick-blue-2   "#00354D")
(defvar slick-blue+1   "#A0E2FF")
(defvar slick-blue+2   "#ECF9FF")
(defvar slick-grey-0   "#F6F6F6")
(defvar slick-grey-1   "#202020")
(defvar slick-grey-2   "#101010")
(defvar slick-grey+1   "#404040")
(defvar slick-grey+2   "#D0D0D0")

(custom-theme-set-variables
 'slick
 '(slick-orange-0 "#FFA139")
 '(slick-orange-1 "#80684E")
 '(slick-orange-2 "#4D2800")
 '(slick-orange+1 "#FFD09C")
 '(slick-orange+2 "#FFF6EB")
 '(slick-pink-0   "#FF398F")
 '(slick-pink-1   "#804E64")
 '(slick-pink-2   "#4D0021")
 '(slick-pink+1   "#FF9CC7")
 '(slick-pink+2   "#FFEBF4")
 '(slick-green-0  "#ABFF39")
 '(slick-green-1  "#6B804E")
 '(slick-green-2  "#2C4D00")
 '(slick-green+1  "#D5FF9C")
 '(slick-green+2  "#F7FFEB")
 '(slick-blue-0   "#42C6FF")
 '(slick-blue-1   "#507180")
 '(slick-blue-2   "#00354D")
 '(slick-blue+1   "#A0E2FF")
 '(slick-blue+2   "#ECF9FF")
 '(slick-grey-0   "#F6F6F6")
 '(slick-grey-1   "#202020")
 '(slick-grey-2   "#101010")
 '(slick-grey+1   "#404040")
 '(slick-grey+2   "#D0D0D0")
 )

(custom-theme-set-faces
 'slick

 `(magit-branch ((t (:inherit magit-header :foreground ,slick-blue-0 :weight bold))))
 `(magit-diff-del ((t (:inherit diff-removed :foreground ,slick-pink-0 :background ,slick-grey-1))))
 `(magit-diff-add ((t (:inherit diff-added :foreground ,slick-green-0 :background ,slick-grey-1))))
 `(magit-item-highlight ((t (:background ,slick-blue-1 :inherit nil))))
 `(magit-log-sha1 ((t (:foreground ,slick-green-1))))

 `(show-paren-match-face ((t (:foreground ,slick-pink+2 :background ,slick-green-1))))
 `(show-paren-mismatch-face ((t (:foreground ,slick-green+2 :background ,slick-pink-1))))

 `(header-line ((t (:box nil :foreground ,slick-orange+1 :background ,slick-grey-2 :inherit (mode-line)))))
 `(escape-glyph ((t (:weight bold :foreground ,slick-pink-1))))
 `(region ((t (:inverse-video nil :background ,slick-blue-2))))
 `(highlight ((t (:foreground ,slick-orange+2 :background ,slick-blue-2))))
 `(cursor ((t (:foreground ,slick-grey-2 :background ,slick-orange+2))))
 `(minibuffer-prompt ((t (:foreground ,slick-blue+1))))
 `(secondary-selection ((t (:background ,slick-blue-1))))
 `(trailing-whitespace ((t (:background ,slick-pink-2))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 `(hl-line ((t (:background ,slick-blue-2 :inherit nil))))

 `(font-lock-builtin-face ((t (:foreground ,slick-green-0))))
 `(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground ,slick-green-0 :inherit (bold)))))
 `(font-lock-function-name-face ((t (:foreground ,slick-green-0))))
 `(font-lock-comment-face ((t (:foreground ,slick-blue-1))))
 `(font-lock-comment-delimiter-face ((t (:foreground ,slick-pink-1 :inherit (font-lock-comment-face)))))
 `(font-lock-doc-face ((t (:foreground ,slick-pink-1 :inherit (font-lock-string-face)))))
 `(font-lock-negation-char-face ((t (:foreground ,slick-pink-1))))
 `(font-lock-constant-face ((t (:foreground ,slick-blue+1))))
 `(font-lock-keyword-face ((t (:weight bold :foreground ,slick-pink-0))))
 `(font-lock-preprocessor-face ((t (:foreground ,slick-pink-0 :inherit (font-lock-builtin-face)))))
 `(font-lock-regexp-grouping-construct ((t (:weight bold :foreground ,slick-orange-0 :inherit (bold)))))
 `(font-lock-variable-name-face ((t (:foreground ,slick-orange-0))))
 `(font-lock-string-face ((t (:foreground ,slick-green+1))))
 `(font-lock-type-face ((t (:foreground ,slick-blue-0))))
 `(font-lock-warning-face ((t (:weight bold :foreground ,slick-orange-1 :inherit (error)))))

 '(button ((t (:underline (:color foreground-color :style line) :inherit (link)))))
 `(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground ,slick-blue-0))))
 `(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground ,slick-blue-1 :inherit (link)))))
 `(fringe ((t (:foreground ,slick-orange+2 :background ,slick-grey-1))))
 `(tooltip ((((class color)) (:inherit (variable-pitch) :foreground ,slick-grey-2 :background "lightyellow")) (t (:inherit (variable-pitch)))))

 `(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground ,slick-blue-1 :background ,slick-grey-2))))
 `(mode-line-buffer-id ((t (:weight bold :foreground ,slick-blue-0))))
 '(mode-line-emphasis ((t (:weight bold))))
 `(mode-line-highlight ((t (:box (:line-width 2 :color ,slick-blue-2 :style released-button))) (t (:inherit (highlight)))))
 `(mode-line-inactive ((t (:weight light :box (:line-width -1 :color nil :style released-button) :foreground ,slick-blue-2 :background ,slick-grey-1 :inherit (mode-line)))))

 `(powerline-active1 ((t (:inherit mode-line :background ,slick-grey-1 :foreground ,slick-green-1))))
 `(powerline-active2 ((t (:inherit mode-line :background ,slick-grey-1 :foreground ,slick-orange-0))))
 `(powerline-inactive1 ((t (:inherit mode-line :background ,slick-grey-1 :foreground ,slick-grey+1))))
 `(powerline-inactive2 ((t (:inherit mode-line :background ,slick-grey-1 :foreground ,slick-grey+1))))

 `(isearch ((t (:foreground ,slick-orange-0 :background ,slick-grey-2))))
 `(isearch-fail ((t (:foreground ,slick-orange+2 :background ,slick-pink-0))))
 `(lazy-highlight ((t (:foreground ,slick-orange+1 :background ,slick-grey-2))))
 `(match ((t (:weight bold :foreground ,slick-green-0 :background ,slick-grey-2))))
 '(query-replace ((t (:inherit (isearch)))))

 `(default ((t (:family "Source_Code_Pro" :foundry "apple" :height 120 :foreground ,slick-orange+2 :background ,slick-grey-1)))))
